// <auto-generated />
using System;
using FinalWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423030722_AddCarAndAnimalTables")]
    partial class AddCarAndAnimalTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalWebAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FavoriteFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            FavoriteFood = "Grain",
                            Gender = "Female",
                            Name = "Lisa",
                            Species = "Cow"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            FavoriteFood = "Grass",
                            Gender = "Male",
                            Name = "Larry",
                            Species = "Goat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 17,
                            FavoriteFood = "Hay",
                            Gender = "Male",
                            Name = "Gold Ship",
                            Species = "Horse"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 30,
                            FavoriteFood = "Carrots",
                            Gender = "Male",
                            Name = "Bugs",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 5,
                            FavoriteFood = "Stuff",
                            Gender = "Male",
                            Name = "John Pork",
                            Species = "Pig"
                        });
                });

            modelBuilder.Entity("FinalWebAPI.Models.Candle", b =>
                {
                    b.Property<int>("CandleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FragranceNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandleId");

                    b.ToTable("Candles");

                    b.HasData(
                        new
                        {
                            CandleId = 1,
                            Brand = "Yankee Candle",
                            Description = "Sweet and spicy fragrance reminiscent of a day of baking.",
                            FragranceNotes = "vanilla bean, chocolate, cocoa, malted sugar",
                            Name = "Vanilla Cupcake"
                        },
                        new
                        {
                            CandleId = 2,
                            Brand = "Yankee Candle",
                            Description = "Experience a cozy, secluded coastal escape.",
                            FragranceNotes = "cottonwood, driftwood, orange blossoms, acacia",
                            Name = "Seaside Woods"
                        },
                        new
                        {
                            CandleId = 3,
                            Brand = "Bath and Body Works",
                            Description = "You'll enjoy every bit of this savory, fresh-from-the-oven fragrance—no starter needed.",
                            FragranceNotes = "baked sourdough, whipped butter, olive oil drizzle",
                            Name = "Homemade Sourdough"
                        },
                        new
                        {
                            CandleId = 4,
                            Brand = "Bath and Body Works",
                            Description = "Woodsy, mysterious home fragrance turned rich, refined fragrance icon.",
                            FragranceNotes = "rich mahogany, black teakwood, dark oak, lavender",
                            Name = "Mahogany Teakwood"
                        },
                        new
                        {
                            CandleId = 5,
                            Brand = "Yankee Candle",
                            Description = "As you step into your favorite bakery, scents of fresh Gariguette strawberries topped with vanilla essence and Chantilly cream flood the room.",
                            FragranceNotes = "strawberry, lemon zest, cake batter, vanilla, white musk, baked notes",
                            Name = "Strawberry Swirl"
                        });
                });

            modelBuilder.Entity("FinalWebAPI.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Milage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Ford",
                            Milage = 65000,
                            Model = "F-150",
                            VIN = "1FTFW1C85MKF12816",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Volkswagen",
                            Milage = 325356,
                            Model = "Passat",
                            VIN = "WVWJL9AN8AE059036",
                            Year = 2010
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Saturn",
                            Milage = 426965,
                            Model = "SL",
                            VIN = "1G8ZF5284YZ202749",
                            Year = 2000
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Chrysler",
                            Milage = 183260,
                            Model = "Pacifica",
                            VIN = "2A8GF68X88R144021",
                            Year = 2008
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Porsche",
                            Milage = 54721,
                            Model = "911",
                            VIN = "WP0AG2A9XPS252314",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("FinalWebAPI.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamMemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamMemberId = 1,
                            Birthdate = new DateTime(2005, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Application Development",
                            FullName = "Maria Smith",
                            YearInProgram = "Pre-Junior"
                        },
                        new
                        {
                            TeamMemberId = 2,
                            Birthdate = new DateTime(2004, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Chemical Engineering",
                            FullName = "Reese Howard",
                            YearInProgram = "Pre-Junior"
                        },
                        new
                        {
                            TeamMemberId = 3,
                            Birthdate = new DateTime(2002, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Nursing",
                            FullName = "Lauren Riihimaki",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            TeamMemberId = 4,
                            Birthdate = new DateTime(2006, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Music Education",
                            FullName = "Peter McWallen",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            TeamMemberId = 5,
                            Birthdate = new DateTime(2007, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "English Literature",
                            FullName = "Ryan Faulkner",
                            YearInProgram = "Freshman"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
