// <auto-generated />
using System;
using FinalWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422144057_AddDataToTables")]
    partial class AddDataToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalWebAPI.Models.Candle", b =>
                {
                    b.Property<int>("CandleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FragranceNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandleId");

                    b.ToTable("Candles");

                    b.HasData(
                        new
                        {
                            CandleId = 1,
                            Brand = "Yankee Candle",
                            Description = "Sweet and spicy fragrance reminiscent of a day of baking.",
                            FragranceNotes = "vanilla bean, chocolate, cocoa, malted sugar",
                            Name = "Vanilla Cupcake"
                        },
                        new
                        {
                            CandleId = 2,
                            Brand = "Yankee Candle",
                            Description = "Experience a cozy, secluded coastal escape.",
                            FragranceNotes = "cottonwood, driftwood, orange blossoms, acacia",
                            Name = "Seaside Woods"
                        },
                        new
                        {
                            CandleId = 3,
                            Brand = "Bath and Body Works",
                            Description = "You'll enjoy every bit of this savory, fresh-from-the-oven fragrance—no starter needed.",
                            FragranceNotes = "baked sourdough, whipped butter, olive oil drizzle",
                            Name = "Homemade Sourdough"
                        },
                        new
                        {
                            CandleId = 4,
                            Brand = "Bath and Body Works",
                            Description = "Woodsy, mysterious home fragrance turned rich, refined fragrance icon.",
                            FragranceNotes = "rich mahogany, black teakwood, dark oak, lavender",
                            Name = "Mahogany Teakwood"
                        },
                        new
                        {
                            CandleId = 5,
                            Brand = "Yankee Candle",
                            Description = "As you step into your favorite bakery, scents of fresh Gariguette strawberries topped with vanilla essence and Chantilly cream flood the room.",
                            FragranceNotes = "strawberry, lemon zest, cake batter, vanilla, white musk, baked notes",
                            Name = "Strawberry Swirl"
                        });
                });

            modelBuilder.Entity("FinalWebAPI.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamMemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamMemberId = 1,
                            Birthdate = new DateTime(2005, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Application Development",
                            FullName = "Maria Smith",
                            YearInProgram = "Pre-Junior"
                        },
                        new
                        {
                            TeamMemberId = 2,
                            Birthdate = new DateTime(2004, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Chemical Engineering",
                            FullName = "Reese Howard",
                            YearInProgram = "Pre-Junior"
                        },
                        new
                        {
                            TeamMemberId = 3,
                            Birthdate = new DateTime(2002, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Nursing",
                            FullName = "Lauren Riihimaki",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            TeamMemberId = 4,
                            Birthdate = new DateTime(2006, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Music Education",
                            FullName = "Peter McWallen",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            TeamMemberId = 5,
                            Birthdate = new DateTime(2007, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "English Literature",
                            FullName = "Ryan Faulkner",
                            YearInProgram = "Freshman"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
